[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bedrock-server-manager"
version = "3.1.2"
authors = [
  { name="ZVortex11325", email="zvortex11325-github@outlook.com" },
]
description = "A manager for Minecraft Bedrock Dedicated Servers"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
	"Environment :: Console",
	"Topic :: Games/Entertainment",
]

dependencies = [
    "requests",
    "psutil",
    'pywin32; sys_platform == "win32"',
    "flask",
    "flask-wtf",
    "flask-jwt-extended",
    "waitress"
]

[project.optional-dependencies]
color = ["colorama"]

keywords = ["minecraft", "bedrock", "server"]

[project.urls]
Repository = "https://github.com/dmedina559/bedrock-server-manager.git"
"Bug Tracker" = "https://github.com/DMedina559/bedrock-server-manager/issues"
Changelog = "https://github.com/DMedina559/bedrock-server-manager/blob/main/CHANGELOG.md"

[tool.setuptools.packages.find]
where = ["."]
include = ["bedrock_server_manager*"]

[project.scripts]
bedrock-server-manager = "bedrock_server_manager:main"

[tool.setuptools.package-data]
"bedrock_server_manager.web" = [
    "templates/**/*",
    "static/**/*"
]

[tool.pytest.ini_options]
testpaths = [".test"]