[project]
name = "rnadvisor"
version = "2.0.0"
description = "RNAdvisor is a wrapper tool to compute RNA 3D structure quality assessment."
readme = "README.md"
authors = [
    { name = "clementbernardd", email = "clementbernardd@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "click>=8.1.8",
    "loguru>=0.7.3",
    "pandas>=1.3.5",
    "tqdm>=4.67.1",
]

[project.scripts]
rnadvisor = "rnadvisor.rnadvisor_cli:main"

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"rnadvisor" = ["docker-compose.slim.yaml"]
