# pyproject.toml

[project]
authors = [{ name = "Alex Basile", email = "basileaw@gmail.com" }]
dependencies = [
  "boto3",
  "httpx",
  "rich",
  "prompt-toolkit",
  "terminaide (>=0.1.6)",
]
description = "A pretty command line interface for LLM chat."
license = "MIT"
name = "chatline"
readme = "README.md"
requires-python = ">=3.12"
version = "0.2.5"

[project.optional-dependencies]
dev = ["fastapi", "uvicorn", "requests>=2.32.3"]

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
