[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dde-agents"
version = "0.0.3.18"
description = "This is a SDK to help you create AI agents."
readme = "README.md"
requires-python = ">=3.7"
license = {text = "Apache-2.0"}
dependencies = [
    "openai",
]

[project.urls]
Homepage = "https://github.com/DDE-64-bit/DDE-Agents"
