[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aspcore"
version = "0.0.4"
authors = [
    {name = "Jesper BrunnstrÃ¶m", email = "jesper_brunnstrom@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "numpy",
    "scipy",
    "numba",
    "numexpr",
    "jax",
    "matplotlib",
    "tensorly",
    "samplerate",
    "tikzplotlib"
]

[project.optional-dependencies]
test = [
    "pytest",
    "hypothesis",
    "aspsim",
]

[project.urls]
Documentation = "https://sounds-research.github.io/aspcore/"
Repository = "https://github.com/SOUNDS-RESEARCH/aspcore"