[project]
name = "defix-package-logger"
version = "0.1.9"
description = "DeFiX internal package for service logging"
readme = "README.md"
authors = [
    { name = "Mykhailo Kuzmin", email = "guywithnothing56@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "python-json-logger>=3.3.0",
]

[project.scripts]
defix-package-logger = "defix_package_logger:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
bump_message = "ci: version bump to $new_version"
update_changelog_on_bump = true
version_provider = "uv"
