[build-system]
requires = [
  "setuptools>=70",
  "wheel>=0.40.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "climalysis"
version = "0.1.1"
description = "A comprehensive toolkit for climate impact analysis."
readme = "README.md"
requires-python = ">=3.7"
license = "GPL-3.0-or-later"

authors = [
  { name = "Jake Casselman", email = "jake.w.casselman@gmail.com" }
]

keywords = [
  "python", "climate", "analysis", "climate analysis", "climate data", "impact analysis"
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Atmospheric Science",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
]

dependencies = [
  "numpy>=1.26,<2.3",          
  "scikit_learn>=1.2.1,<1.5",
  "scipy>=1.9.3,<1.13",
  "statsmodels>=0.13.5,<0.15",
  "xarray>=2023.3.0,<2024.0"
]

[project.optional-dependencies]
dev = [
  "pytest",
  "black",
  "mypy"
]

[project.urls]
Homepage = "https://github.com/Climalysis/climalysis"
Documentation = "https://climalysis.readthedocs.io/en/latest/"

[tool.setuptools]
packages = ["climalysis"]