[project]
name = "mseep-employee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beeai-framework>=0.1.4",
    "mcp[cli]>=1.3.0",
    "requests>=2.32.3",
]

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"
