[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mrjet"
version = "0.1.2"
authors = [
  { name = "cailurus"},
]
description="simple m3u8 downloader for missav"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "curl-cffi>=0.9.0",
    "m3u8>=6.0.0",
    "pym3u8downloader>=0.1.8",
    "requests>=2.32.3",
    "cloudscraper>=1.2.71",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.scripts]
mrjet = "mrjet.cli:main"
[project.urls]
"Homepage" = "https://github.com/cailurus/mrjet"
