[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ug_tagung"
version = "1.3.17"
description = "Adressverwaltung für Tagungen"
readme = "README.md"
licence = {file = "LICENSE"}
requires-python = ">=3.10"
dependencies = [
    "ugbib_divers",
    "ugbib_modell",
    "ugbib_tkinter",
    "ugbib_werkzeug",
    "Pillow",
    "psycopg2-binary",
    "PyYAML",
    "rich",
]
autors = [
    {name = "Ulrich Goebel", email = "ulrich@fam-goebel.de"},
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
#     "Development Status :: 4 - Beta",
    "Development Status :: 5 - Production/Stable",
]

# Im Folgenden:
# Die nächste Zeilen mit artifacts includiert Dateien, die sonst wegen .gitignore
# ausgeschlossen würden.
# Vgl. https://hatch.pypa.io/latest/config/build/#file-selection

[tool.hatch.build.targets.wheel]
packages = ["src/ug_tagung"]
artifacts = [
    "src/ug_tagung/*.yaml",
    "src/ug_tagung/*.sh",
    "src/ug_tagung/*.ps1"]

[tool.hatch.build.targets.sdist]
artifacts = [
    "src/ug_tagung/*.yaml",
    "src/ug_tagung/*.sh",
    "src/ug_tagung/*.ps1"]

[tool.setuptools]
packages = ["ug_tagung"]

[tool.setuptools.entry-points.console_scripts]
Tagung = "ug_tagung.Tagung:main"
