[build-system]
requires = [
    "hatchling",
    "uv-dynamic-versioning",
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
packages = [
    "logfire_mcp",
]

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "FA",
    "UP",
    "RUF100",
]
ignore = [
    "UP031",
]

[tool.ruff.lint.isort]
combine-as-imports = true

[project]
name = "mseep-logfire-mcp"
dynamic = [
    "version",
]
description = "The Logfire MCP server! ðŸ”"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "logfire>=3.7.1",
    "mcp[cli]>=1.4.1",
]

[project.license]
text = "MIT"

[project.scripts]
logfire-mcp = "logfire_mcp.__main__:main"

[project.urls]
Homepage = "https://github.com/pydantic/logfire-mcp"
Repository = "https://github.com/pydantic/logfire-mcp"
Issues = "https://github.com/pydantic/logfire-mcp/issues"

[dependency-groups]
dev = [
    "ruff",
]
