[tool.poetry]
name = "mmdit-pytorch"
version = "0.2.7"
description = "A standalone implementation of a single block of Multimodal Diffusion Transformer (MMDiT) originally proposed in Scaling Rectified Flow Transformers for High-Resolution Image Synthesis (https://arxiv.org/abs/2403.03206) in PyTorch with minimal dependencies."
authors = ["Kenny Stryker <nggkenny@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "mmdit" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed"
]
homepage = "https://github.com/KennyStryker/mmdit-pytorch.git"
repository = "https://github.com/KennyStryker/mmdit-pytorch.git"

[tool.poetry.dependencies]
python = ">=3.12"
einops = "^0.8.1"
torch = "^2.6.0"
numpy = "^2.2.4"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
black = {version = "24.4.2", extras = ["jupyter"]}
pylint = "^3.2.6"
mypy = "^1.11.1"
pytest-asyncio = "^0.24.0"
pre-commit = "^3.8.0"
pytest-cov = "^5.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
