[project]
name = "aivk_qq"
version = "0.1.3.0"
description = "AIVK-QQ：一个强大的QQ机器人框架，集成MCP服务器、CLI工具、Napcat.Shell启动器和Napcat API SDK于一体，为AI驱动的QQ交互提供全方位支持"
readme = "README.md"
authors = [
    { name = "LIghtJUNction", email = "lightjunction.me@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aivk>=0.3.2.20",
    "click>=8.1.8",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "tqdm>=4.67.1",
    "websockets>=15.0.1",
]

[project.scripts]
aivk-qq = "aivk_qq.cli:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
