[tool.poetry]
name = "py-net-diags"
version = "0.1.5"
description = "Gets various network diagnostics for a pc"
authors = ["VinnyVanGogh <133192356+VinnyVanGogh@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "py_net_diags"}]

[tool.poetry.dependencies]
python = "^3.12"
cw-rpa = "^1.0.1"
psutil = "^7.0.0"
tenacity = "^9.1.2"
python-dotenv = "^1.1.0"
xhtml2pdf = "^0.2.17"
speedtest-cli = "^2.1.3"
markdown = "^3.8"
speedcheck = { version = "^0.0.5", optional = true }

[tool.poetry.extras]
speedcheck = ["speedcheck"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
