[project]
name = "set-mcp"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "prem", email = "prem.ch@ku.th" }
]
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.1.1",
    "httpx>=0.28.1",
    "pandas>=2.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pyright>=1.1.399",
]

[project.scripts]
set-mcp = "set_mcp.__main__:main"
