[project]
name = "hydrostab"
description = "Evaluation of hydrograph stability, detecting oscillations in data from hydrodynamic models."
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
version = "0.2.0rc1"
dependencies = ["pandas"]

[project.optional-dependencies]
ras = ["rashdf"]
exp = ["scipy"]
dev = ["pre-commit", "ruff", "pytest", "pytest-cov"]
nb = ["jupyterlab", "jupytext", "ipywidgets", "matplotlib", "rashdf"]
# docs = ["sphinx", "numpydoc", "sphinx_rtd_theme"]

[project.urls]
repository = "https://github.com/fema-ffrd/hydrostab"

[tool.pytest.ini_options]
pythonpath = "."
testpaths = "tests"

[tool.ruff.lint]
select = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D"]
"docs/**" = ["D"]

[tool.setuptools]
packages = ["hydrostab"]
