name: ğŸ“¦ Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Memicu alur kerja pada push tag versi, misalnya v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: 3.12

      - name: ğŸ·ï¸ Extract version from Git tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: ğŸ§¹ Clear directory
        run: rm -rf dist

      - name: ğŸ”¨ Build package
        run: uv build

      - name: ğŸš€ Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }}
