[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "phonic-python"
version = "0.1.5"
description = "The official Python library for the Phonic API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "isort>=6.0.0",
    "loguru>=0.7.3",
    "numpy>=2.2.2",
    "pyaudio==0.2.14",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "scipy>=1.15.1",
    "sounddevice>=0.5.1",
    "typing-extensions>=4.12.2",
    "websockets==15.0.0",
]

[tool.setuptools]
packages = ["phonic"]