[project]
name = "tdoa-mcp-contract-filing"
version = "0.1.1"
description = "Tongda OA integration through the Model Context Protocol"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "Liu Hao", email = "liu.hao1443@gmail.com"}
]
license = "Apache-2.0"
dependencies = [
    "bs4==0.0.2",
    "fastmcp==0.4.1",
    "loguru==0.7.3",
    "markdown==3.7",
    "pyyaml==6.0.2",
    "requests==2.32.3"
]

[project.scripts]
tdoa-mcp-contract-filing = "src.server:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "."}

[project.urls]
"Homepage" = "https://github.com/LiuHao-1443/tdoa-mcp"
"Bug Tracker" = "https://github.com/LiuHao-1443/tdoa-mcp/issues"