[tool.poetry]
name = "s3_map"
version = "0.1.0"
description = ""
authors = ["Olivier Duchaine <olivier.duchaine@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.19.7"
boto3-stubs = { extras = ["s3"], version = "^1.19.7" }
typer = "^0.4.0"
pytz = "^2021.3"
tabulate = "^0.8.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
