[project]
name = "yh_olap"
version = "2.0.1"
authors = [
  { name="zhang3", email="675942084@qq.com" },
]
description = "YH_OLAPçš„API"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

#[project.urls]
#Homepage = "https://github.com/pypa/sampleproject"
#Issues = "https://github.com/pypa/sampleproject/issues"