[project]
name = "spider-py3"
version = "0.1.0.20250201"
description = ""
authors = [
    { name = "mathewgeola", email = "mathewgeola@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "requests (>=2.32.3,<3.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "aiohttp (>=3.11.11,<4.0.0)",
    "drissionpage (>=4.1.0.17,<5.0.0.0)",
    "parsel (>=1.9.1,<2.0.0)",
    "htmlmin (>=0.1.12,<0.2.0)",
    "fake-useragent (>=2.0.3,<3.0.0)",
    "bs4 (>=0.0.2,<0.0.3)",
    "furl (>=2.1.3,<3.0.0)",
    "jsonpath (>=0.82.2,<0.83.0)",
    "tldextract (>=5.1.3,<6.0.0)",
    "pyexecjs (>=1.5.1,<2.0.0)",
    "py-mini-racer (>=0.6.0,<0.7.0)",
    "colorlog (>=6.9.0,<7.0.0)",
    "pycryptodome (>=3.21.0,<4.0.0)",
    "numpy (>=2.2.1,<3.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "xlwt (>=1.3.0,<2.0.0)",
    "xlrd (>=2.0.1,<3.0.0)",
    "opencv-python (>=4.10.0.84,<5.0.0.0)",
    "pymysql (>=1.1.1,<2.0.0)",
    "redis (>=5.2.1,<6.0.0)",
    "pymongo (>=4.10.1,<5.0.0)",
    "sqlalchemy (>=2.0.36,<3.0.0)",
    "cx-oracle (>=8.3.0,<9.0.0)",
    "ujson (>=5.10.0,<6.0.0)",
    "pillow (>=11.1.0,<12.0.0)",
    "pika (>=1.3.2,<2.0.0)",
    "socksio (>=1.0.0,<2.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "ddddocr (>=1.5.6,<2.0.0)",
    "matplotlib (>=3.10.0,<4.0.0)",
    "jinja2 (>=3.1.5,<4.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "tenacity (>=9.0.0,<10.0.0)",
    "sqlparse (>=0.5.3,<0.6.0)",
    "arrow (>=1.3.0,<2.0.0)",
    "oss2 (>=2.19.1,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
packages = [
    { include = "spiderpy3", from = "src" }
]
