[project]
name = "mcp-server-demo"
version = "0.4.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Seemant Tripathi", email = "tripathiseemant766@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "build>=1.2.2.post1",
    "twine>=6.1.0",
]

[project.scripts]
mcp-server-demo = "mcp_server_demo:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
