[project]
name = "multinear"
version = "0.1.8"
description = "Multinear platform"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "autoevals>=0.0.105",
    "fastapi[standard]>=0.103",
    "jinja2>=3.1.4",
    "jsonpath-ng>=1.7.0",
    "openai>=1.55.0",
    "rich>=13.9.4",
    "sqlalchemy>=2.0.36",
    "tqdm>=4.67.0",
    "uvicorn[standard]>=0.23",
]

[project.scripts]
multinear = "multinear.cli.main:main"
