[project]
name = "mcp-server-demo"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "build>=1.2.2.post1",
    "mcp[cli]>=1.6.0",
    "requests>=2.31.0",
    "twine>=6.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
