[project]
name = "universalinit"
version = "0.1.15"
description = ""
authors = [
    {name = "Zoltan Kuscsik",email = "zoltan@s57.io"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "PyYAML",
    "pytest (>=8.3.4,<9.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "universalinit"
version = "0.1.15"
description = ""
readme = "README.md"
authors = ["Zoltan Kuscsik <zoltan@s57.io>"]
packages = [
    { from = "src", include = "universalinit" }
]

[tool.poetry.dependencies]
python = ">=3.11"
PyYAML = "*"
pytest = ">=8.3.4,<9.0.0"

[tool.poetry.scripts]
uniinit = "universalinit.cli:main"
