[project]
name = "near-omni-client"
version = "0.0.1"
description = "Minimal Python library to interact with the NEAR blockchain and Chain Signatures"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "base58>=2.1.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "py-near-primitives>=0.2.3",
    "pydantic>=2.11.3",
    "pynacl>=1.5.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
]
