[project]
name = "supurr-sdk"
version = "0.1.5"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = "==3.10.15"
dependencies = [
    "web3 (==5.31.4)",
    "setuptools (>=78.1.0,<79.0.0)"
]

[tool.poetry]
packages = [{include = "supurr_sdk", from = "src"}]


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
