[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "preempt"
version = "0.1.4"
description = "Sanitize text containing PII attributes"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "annotated-types==0.7.0",
    "anyio==4.9.0",
    "certifi==2025.1.31",
    "charset-normalizer==3.4.1",
    "distro==1.9.0",
    "fastchat==0.1.0",
    "filelock==3.18.0",
    "fsspec==2025.3.2",
    "h11==0.14.0",
    "httpcore==1.0.7",
    "httpx==0.28.1",
    "huggingface-hub==0.30.1",
    "idna==3.10",
    "jinja2==3.1.6",
    "jiter==0.9.0",
    "markupsafe==3.0.2",
    "mpmath==1.3.0",
    "names==0.3.0",
    "names-dataset==3.1.0",
    "networkx==3.4.2",
    "numpy==2.2.4",
    "nvidia-cublas-cu12==12.4.5.8",
    "nvidia-cuda-cupti-cu12==12.4.127",
    "nvidia-cuda-nvrtc-cu12==12.4.127",
    "nvidia-cuda-runtime-cu12==12.4.127",
    "nvidia-cudnn-cu12==9.1.0.70",
    "nvidia-cufft-cu12==11.2.1.3",
    "nvidia-curand-cu12==10.3.5.147",
    "nvidia-cusolver-cu12==11.6.1.9",
    "nvidia-cusparse-cu12==12.3.1.170",
    "nvidia-cusparselt-cu12==0.6.2",
    "nvidia-nccl-cu12==2.21.5",
    "nvidia-nvjitlink-cu12==12.4.127",
    "nvidia-nvtx-cu12==12.4.127",
    "openai==1.70.0",
    "packaging==24.2",
    "protobuf==6.30.2",
    "pycountry==24.6.1",
    "pycryptodome==3.10.1",
    "pydantic==2.11.1",
    "pydantic-core==2.33.0",
    "pyfpe==0.10.3",
    "pyyaml==6.0.2",
    "regex==2024.11.6",
    "requests==2.32.3",
    "safetensors==0.5.3",
    "sentencepiece==0.2.0",
    "sniffio==1.3.1",
    "sympy==1.13.1",
    "tokenizers==0.21.1",
    "torch==2.6.0",
    "tqdm==4.67.1",
    "transformers==4.50.3",
    "triton==3.2.0",
    "typing-extensions==4.13.0",
    "typing-inspection==0.4.0",
    "urllib3==2.3.0",
]
