[project]
name = "llm-fragments-doc"
version = "0.1.0"
description = "Load documents as fragments"
readme = "README.md"
authors = [{ name = "Maximilian Bode" }]
license = {text = "Apache-2.0"}
classifiers = [
    "License :: OSI Approved :: Apache Software License",
]
requires-python = ">=3.9, <3.13"
dependencies = [
    "docling>=2.30.0",
    "llm>=0.24",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = [
    "llm-fragments-doc",
]

[dependency-groups]
dev = [
    "fpdf2>=2.8.2",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
]

[project.entry-points.llm]
fragments_doc = "llm_fragments_doc"
