[project]
name = "genoray"
version = "0.4.0"
description = "Add your description here"
authors = [{ name = "David Laub", email = "dlaub@ucsd.edu" }]
readme = "README.md"
license = { file = "LICENSE.txt" }
requires-python = ">=3.9"
dependencies = [
    "cyvcf2>=0.31.1",
    "hirola>=0.3.0",
    "numpy",
    "pgenlib>=0.92.0",
    "polars>=1.27.1",
    "pyranges==0.1.3",
    "typing-extensions>=4.13.2",
    "pandas",
    "pyarrow>=19.0.1",
    "setuptools>=78.1.0", # uv misses this dependency for pyranges
    "tqdm>=4.67.1",
    "phantom-types>=3.0.2",
    "more-itertools>=10.6.0",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver2"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true
annotated_tag = true

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
