[project]
name = "clickhouse-json"
version = "0.1.0002"
description = ""
authors = [
    {name = "Vladimir Muzychenko",email = "vladimir.muzychenko@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "clickhouse-connect (>=0.8.15,<0.9.0)"
]

[tool.poetry]
packages = [{include = "clickhouse_json", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
