[project]
name = "guiji-mcp"
version = "0.0.5"
description = "create meta human by guiji api."
authors = [
    { name = "weichi", email = "weichi@guiji.ai" },
]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
keywords = [
    "guiji",
    "mcp",
    "create-meta",
]
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.6.0",
    "aiohttp>=3.11.16",
    "fastapi==0.109.2",
    "python-dotenv~=1.0.1",
    "httpx==0.28.1",
]

[project.scripts]
guiji-mcp = "gj_meta_mcp.server:main"

[project.optional-dependencies]
dev = [
    "pre-commit==3.6.2",
    "fastmcp==0.4.1",
    "pytest==8.0.0",
    "pytest-cov==4.1.0",
    "build>=1.0.3",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"
