[project]
name = "mcp-server-monday"
version = "0.2.8"
description = "MCP Server for monday.com"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
 "mcp[cli]>=1.2.1",
 "monday>=2.0.1",
 "requests>=2.32.3",
 "ruff>=0.9.6",
]

[[project.authors]]
name = "Jovan Sakovic"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
  "src/mcp_server_monday/*.py",
]

[project.scripts]
mcp-server-monday = "mcp_server_monday:main"

[project.urls]
Homepage = "https://github.com/sakce/mcp-server-monday/"
