[project]
name="hopsa"
version = "0.2.1"
description = "Utilities that I use regularly"
readme = "README.md"
authors = [
    { name = "Hopsakee", email = "jdejong@posteo.nl" }
]
requires-python=">=3.11"
dependencies = [
    "ipython>=9.1.0",
    "nbformat>=5.10.4",
    "pip>=25.0.1",
    "pydantic>=2.11.3",
]

[project.scripts]
hopsa = "hopsa:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "nbdev>=2.4.2",
]
