[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "exportmd"
version = "0.1.0"
authors = [
  { name="dgo8", email="your.email@example.com" },
]
description = "A Python package that executes code blocks within markdown and exports to various formats"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "markdown>=3.3.0",
    "beautifulsoup4>=4.9.0",
    "plotly>=5.0.0",
    "matplotlib>=3.4.0",
    "numpy>=1.20.0",
    "pandas>=1.3.0",
    "python-pptx>=0.6.0",
    "pdf2docx>=0.5.0",
    "weasyprint>=54.0",
    "seaborn>=0.11.0",
    "kaleido>=0.2.0"
]

[project.urls]
"Homepage" = "https://github.com/dgo8/exportmd"
"Bug Tracker" = "https://github.com/dgo8/exportmd/issues"

[tool.setuptools]
packages = ["exportmd", "exportmd.core", "exportmd.exporters", "exportmd.static"]
package-dir = {"" = "."}
include-package-data = true 
