[build-system]
requires = ["flit_core >= 3.12.0, <4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "scrapers"

[project]
name = "torrent-scrapers"
dynamic = ["version"]
authors = [
  { name="Åukasz Flisak", email="lu.dev00@gmail.com" },
]
description = "Simple collection of scrapers of popular torrent sites."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    'beautifulsoup4>=4.13.3',
    'requests>=2.32.3',
    'pydantic>=2.11.3'
]

classifiers = [
    "Programming Language :: Python :: 3.10",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/flisakl/torrent-scrapers"
Issues = "https://github.com/flisakl/torrent-scrapers/issues"
