[tool.poetry]
name = "lovekit"
version = "0.2.0"
description = ""
authors = ["jhnnsrs <jhnnsrs@gmail.com>"]
readme = "README.md"
packages = [{ include = "lovekit" }]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.9.5"
koil = ">=1.0.0"
livekit = "^0.16.3"


[tool.poetry.group.dev.dependencies]
pytest-aiohttp = "^1.0.5"
pytest-cov = "^5.0.0"

[tool.poetry.scripts]
akuire = "akuire.__main__:main"

[tool.pytest.ini_options]
markers = [
    "composition: test composition",
    "external: test external",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
