[project]
name = "greening"
version = "0.4.12"
description = "A creative dev automation engine for launching, documenting, and publishing projects"
authors = [
    { name = "Christopher Greening", email = "chris@christophergreening.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.7"
dependencies = [
    "cookiecutter",
    "requests",
    "importlib_resources"
]

[project.scripts]
greening = "greening.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["greening*"]

[tool.setuptools.package-data]
greening = ["templates/*", "templates/**/*"]
